name: mathinspector
channels:
- conda-forge
- defaults
dependencies:
- PyInstaller
- PyOpenGL
- cloudpickle
- numpy
- pillow
- setuptools
- scikit-image
- scipy
- watchdog
- pip:
  - PyOpenGL_accelerate
  - pygame
  - pyglm
  - ttkthemes
# base
- python<3.9
- pip
