[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "mathinspector/_dist_version.py"
write_to_template = 'VERSION = "{version}"'
